### ISSUE TITLE
期望能提供天气相关信息

### ISSUE THREAD

**Issue by shaonianzhentan** [virzs/Search-Next#17]
Hi！ @virzs  
感谢你创造出这么好用的项目，如果能在界面中提供天气相关信息那就太好了

下图为Edge浏览器默认主页
![image](https://user-images.githubusercontent.com/5294022/161424569-795b9b9d-50e5-42de-a7c0-e7d68743fa68.png)

**Comment by virzs** [comment]
感谢提出需求，这方面已在计划中，近期较忙，请坐和放宽

**Comment by virzs** [comment]
天气已上线
