### ISSUE TITLE
期望导航中能提供快捷搜索功能

### ISSUE THREAD

**Issue by shaonianzhentan** [virzs/Search-Next#19]
后期随着收录的网站越来越多，如果要去查找，可能会需要点时间
如果有一个搜索框，通过模糊匹配快速找到当前需要的网址就好了
![image](https://user-images.githubusercontent.com/5294022/162868193-f8913d3e-0abf-4594-8df3-8e4b31817d22.png)

**Comment by virzs** [comment]
这个功能计划要做，但目前没有时间

所有数据在 `./src/data/navigation/all.ts` 中，欢迎 pr 或稍作等待

**Comment by virzs** [comment]
功能已上线
