### ISSUE TITLE
期望能自定义设置搜索框，透明大小之类的。当然功能更多更好。

### ISSUE THREAD

**Issue by 674804862** [virzs/Search-Next#2]
期望能自定义设置，搜索框透明、尺寸大小、书签修改（或者关闭书签按钮）、时钟样式修改（或者关闭时钟按钮）

**Comment by 674804862** [comment]
期望能自定义设置，搜索框透明、尺寸大小、书签修改（或者关闭书签按钮）、时钟样式修改（或者关闭时钟按钮）

**Comment by virzs** [comment]
近期开始重写设置框相关
