### ISSUE TITLE
输入框会被联想提示遮挡

### ISSUE THREAD

**Issue by Yakumo-Yukari** [virzs/Search-Next#3]
![20211006123300](https://user-images.githubusercontent.com/12076232/136141181-1dfc53d7-9cd5-4b51-b1c3-32e79af7bac6.png)

输入关键字后  输入框就被被遮挡，联想提示框的位置因为展示在下面

**Comment by virzs** [comment]
:rocket: 网页已更新（如果页面没有变化，请清除缓存刷新）。

:bug: 由于切换到正在开发中的新版本，可能会出现因数据兼容性导致的报错，可打开开发者工具，手动清除本地存储解决。

:ok_hand: 关于首页显示效果，正在逐步优化，感谢使用。

**Comment by virzs** [comment]
如果您遇到其他问题，我会尽快回复

**Comment by Yakumo-Yukari** [comment]
> 如果您遇到其他问题，我会尽快回复

好的 已经已经好了
