### ISSUE TITLE
给大佬提供一个参考的搜索网站 很酷

### ISSUE THREAD

**Issue by Yakumo-Yukari** [virzs/Search-Next#4]
目标网站：https://limestart.cn/

这个网站效果很不错  点击时间或者右键就出现快捷导航 ，右上方还有登录账号和设置 感觉蛮不错的

**Comment by virzs** [comment]
这个网站我也收藏过，一些优秀的地方可以参考，但我认为部分操作过程如果做成相同不太好。不过关于设置部分以后可能会做一个弹窗样式的简洁版，集成一些常用设置。
