### ISSUE TITLE
大佬 可以弄个账号注册登录吗 让用户的设置保存在账号了  而不是本地账号

### ISSUE THREAD

**Issue by Yakumo-Yukari** [virzs/Search-Next#5]

**Comment by win100000** [comment]
是的，我也建议搞个QQ或微信登录的，现在人都多设备，手机版也多适配一下，现在网站手机用户也挺多的。

**Comment by virzs** [comment]
账号功能我也考虑过，但考虑到服务器成本还有些其他原因，暂时还是放弃吧。而且我个人认为，出了账号系统的前提是这个项目能带来优秀的体验，而目前功能上还达不到我的预期
